#Importação das bibliotecas

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#Primeira EDA

In [5]:
df = pd.read_csv('/content/ExpVinho.csv', sep='\t')

In [8]:
df.head(5)

,Id,País,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,...,2021,2021.1,2022,2022.1,2023,2023.1,2024,2024.1,2025,2025.1
0,1,Afeganistão,0,0,0,0,0,0,0,0,...,11,46,0,0,0,0,0,0,0,0
1,2,África do Sul,0,0,0,0,0,0,0,0,...,0,0,0,0,117,698,103,1783,0,0
2,3,"Alemanha, República Democrática",0,0,0,0,4168,2630,12000,8250,...,2698,6741,7630,45367,4806,31853,6666,48095,3983,24672
3,4,Angola,0,0,0,0,0,0,0,0,...,0,0,4068,4761,0,0,0,0,0,0
4,5,Anguilla,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df.shape

(144, 114)

In [13]:
df.dtypes

Id         int64
País      object
1970       int64
1970.1     int64
1971       int64
           ...
2023.1     int64
2024       int64
2024.1     int64
2025       int64
2025.1     int64
Length: 114, dtype: object

In [15]:
df.isnull().sum()

Id        0
País      0
1970      0
1970.1    0
1971      0
         ..
2023.1    0
2024      0
2024.1    0
2025      0
2025.1    0
Length: 114, dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.columns.tolist()[:10]

['Id',
 'País',
 '1970',
 '1970.1',
 '1971',
 '1971.1',
 '1972',
 '1972.1',
 '1973',
 '1973.1']

#Reshape da tabela

##Filtrando as colunas de litros e de valor e adicionando em listas.

In [36]:
cols_litros = []

for coluna in df.columns:
  if "." not in coluna and coluna != 'Id' and coluna != 'País':
    cols_litros.append(coluna)

print(cols_litros)

['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [38]:
cols_valor = []

for coluna in df.columns:
  if "." in coluna and coluna != 'Id' and coluna != 'País':
    cols_valor.append(coluna)

print(cols_valor)

['1970.1', '1971.1', '1972.1', '1973.1', '1974.1', '1975.1', '1976.1', '1977.1', '1978.1', '1979.1', '1980.1', '1981.1', '1982.1', '1983.1', '1984.1', '1985.1', '1986.1', '1987.1', '1988.1', '1989.1', '1990.1', '1991.1', '1992.1', '1993.1', '1994.1', '1995.1', '1996.1', '1997.1', '1998.1', '1999.1', '2000.1', '2001.1', '2002.1', '2003.1', '2004.1', '2005.1', '2006.1', '2007.1', '2008.1', '2009.1', '2010.1', '2011.1', '2012.1', '2013.1', '2014.1', '2015.1', '2016.1', '2017.1', '2018.1', '2019.1', '2020.1', '2021.1', '2022.1', '2023.1', '2024.1', '2025.1']